### ISSUE TITLE
WebP Animation

### ISSUE THREAD

**Issue by edikfuks** [mreichelt/webp-android-backport-library#16]
Hello! 
Does this library support webp animation?

Thank you!

**Comment by mreichelt** [comment]
Hi @edikfuks! This library currently does not support WebP animations, though that would be a really cool enhancement!
Currently I am working on getting static ARGB_8888 images right, and I won't have much time for animations in the upcoming months. But contributions are always welcome! :)

**Comment by edikfuks** [comment]
Thank you!

I am trying to integrate FrameSequence library right now. It is available on google git repository https://android.googlesource.com/platform/frameworks/ex/+/master/framesequence . Will let you know how it would work out.
