### ISSUE TITLE
Test app crashes on Android L

### ISSUE THREAD

**Issue by hofmann** [mreichelt/webp-android-backport-library#8]
01-30 12:08:29.616 E/AndroidRuntime(30253): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.marcreichelt.webp_backport.testapp/de.marcreichelt.webp_backport.testapp.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.os.Looper.loop(Looper.java:135)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at java.lang.reflect.Method.invoke(Native Method)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
01-30 12:08:29.616 E/AndroidRuntime(30253): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:151)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:138)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at de.marcreichelt.webp_backport.testapp.MainActivity.onCreate(MainActivity.java:28)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.Activity.performCreate(Activity.java:5933)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
01-30 12:08:29.616 E/AndroidRuntime(30253): 	... 10 more

**Comment by mreichelt** [comment]
Nice work! :)
